### ISSUE TITLE
Add basic formatting to README.MD

### ISSUE THREAD

**Issue by Lisennk** [DmtryJS/WebRemotePC#1]
https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html

**Comment by uonick** [comment]
@Taras-S https://github.com/DmtryJS/WebRemotePC/pull/6 :smiley:

**Comment by Lisennk** [comment]
Nice

**Comment by DmtryJS** [comment]
поправил по возможности
