### ISSUE TITLE
Дублирование настройки пути к приложению

### ISSUE THREAD

**Issue by uonick** [DmtryJS/WebRemotePC#12]
https://github.com/DmtryJS/WebRemotePC/blob/master/class/Control.class.php#L3
Зачем? 
Предлагаю варианты:
- Использовать ini файл
- Использовать yml файл
- Использовать array (return ['path'=>'path'])
- Использовать свойство класса и передавать по наследству

**Comment by DmtryJS** [comment]
Путь может меняться, поэтому передаю его при создании файла. 
В вот чтение из ini,- интересно весьма, как задел на перед, там можно хранить данные для авторизации будет.

**Comment by uonick** [comment]
Не надо хранить данные авторизации в`ini`. Только настройки. 
При этом файл должен быть **недоступен** по прямому пути, например: `http://domain.ltd/config.ini`.
Для этого лучше использовать массив с конфигурацией, а файл не давать выполнять напрямую.
Запретить на прямое чтение/исполнение (через .htaccess например).

**Comment by uonick** [comment]
Пользователей или авторизацию лучше хранить в базе, хотябы sqlite какой-нибудь.
Написать малюсенький классик, который будет работать с базой.
Кстати, DmtryJS говорит о том, что основное направление все-таки javascript? [Electron](http://electron.atom.io/) уже пробовали?

**Comment by DmtryJS** [comment]
про .htaccess, да само собой. Базу сюда делать считаю излишним, хотя в случае с sqlite,-  идея хорошая, в плане ее легкости. Может быть и попробую, "проекту"  всего 3 дня. Честно не ожидал что кого то заинтересует) 
Elecntron я не смотрел, новые фишки в JS появляются быстрей чем я про них узнаю, да и со старыми бы разобраться)

**Comment by uonick** [comment]
Полноценную базу цеплять конечно не стоит) 
Но где-то в недоступном месте настройки должны лежать. 
В первом посте я уже писал варианты =)
_я мимо хабра проходил_ :smile:
