### ISSUE TITLE
Add 'how to install' chapter

### ISSUE THREAD

**Issue by Lisennk** [DmtryJS/WebRemotePC#2]

**Comment by uonick** [comment]
https://github.com/DmtryJS/WebRemotePC/pull/13 :+1: бдыщь!

**Comment by DmtryJS** [comment]
) надо пробовать, я пока не дома. Вечером. Вроде все складно. Спасиб.

**Comment by DmtryJS** [comment]
Спасибо uonick, добавил, осталось перевести на Английский
