### ISSUE TITLE
Follow PSR guidelines 

### ISSUE THREAD

**Issue by Lisennk** [DmtryJS/WebRemotePC#5]
You code a little bit hard to read, PSR following will fix it.
Also visit http://www.phptherightway.com/

**Comment by uonick** [comment]
http://phptherightway.ru/ чтобы почитать на могучем

**Comment by DmtryJS** [comment]
Спасибо за правки. Буду ознакамливаться с PSR

**Comment by Lisennk** [comment]
Issue закрывают после их выполнения, а не после того, как ты их увидел -- потому что на GitHub их можешь выполнить не только ты, а любой желающий ;)

**Comment by DmtryJS** [comment]
да, буду знать.) Раньше кроме коммитов для себя больше ничего не делал, поэтому сейчас "плаваю"

**Comment by uonick** [comment]
@Lisennk 
Не любой желающий а автор. Этим автором может быть как автор репозитория (и мейнтейнеры) так и создавший issue.
